### ISSUE TITLE
Can't generate subtitles after searching anime on bilibili

### ISSUE THREAD

**Issue by Vinzgh24** [AdvMaple/bilibili-subtitle-download-plugin#46]
Hi can you please check this. When I do a search on bilibili and choose anime from the search, script Can't identify video ID, but if I select anime from the homepage the script works fine I think this might be a bug.

**Comment by calavikevin** [comment]
bibili changed video url format when searching (/[nation code]/play)

I'll update soon.

**Comment by calavikevin** [comment]
@AdvMaple please approve the pull request #47

**Comment by AdvMaple** [comment]
merged @calavikevin

**Comment by calavikevin** [comment]
@Vinzgh24 fixed your issue, please check the new version

**Comment by Vinzgh24** [comment]
@calavikevin thanks!
